add velero and minio examples
cnoe-io/idpbuilder pull request #129
Opened 2024-01-18 02:18 UTC by nabuskey

Adds an example of setting up velero and minio locally for backing up objects.

2024-01-25 06:37 UTC, nimakaviani requested changes

2024-01-25 06:37 UTC, nimakaviani commented on examples/local-backup/README.md
> +kubectl -n minio get secret minio -o go-template='{{ range $key, $value := .data }}{{ printf "%s: %s\n" $key ($value | base64decode) }}{{ end }}'
the secret name for my minio instance is `root-creds`. is that the default? show the above name be fixed?

2024-01-25 06:37 UTC, nimakaviani commented on examples/local-backup/demo/backup.yaml
> +    - '*'
probably a good idea to have `nginx-example` listed as the namespace

2024-01-25 06:37 UTC, nimakaviani commented on examples/local-backup/demo/restore.yaml
> +    - '*'
same as above

2024-01-25 06:37 UTC, nimakaviani commented on examples/local-backup/README.md
> +```
This bit is not required. it gets printed every time someone runs the idpBuilder

2024-01-25 06:39 UTC, nimakaviani commented
great stuff overall. left some minor comments!

2024-01-26 02:33 UTC, nabuskey commented
Addressed comments. Please review when you have time

2024-01-26 07:13 UTC, nimakaviani approved these changes
LGTM, thanks!

2024-01-26 07:13 UTC, merged