Provider api
cnoe-io/idpbuilder pull request #183
Opened 2024-03-23 22:10 UTC by greghaynes

2024-03-25 07:29 UTC, cmoulliard commented
Can you please add an issue with the description about the PR ?

2024-03-26 04:52 UTC, nimakaviani requested changes

2024-03-26 04:52 UTC, nimakaviani commented on pkg/controllers/resources/idpbuilder.cnoe.io_custompackages.yaml
> +    controller-gen.kubebuilder.io/version: v0.12.0
looks like you need to bump the version of your controller gen. are you using an older version of idpbuilder or is there any other reason to have this older version used?

2024-03-26 04:52 UTC, nimakaviani commented on pkg/controllers/resources/idpbuilder.cnoe.io_custompackages.yaml
> +              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
these diffs will go away if a newer version of controller gen is used

2024-03-26 04:52 UTC, nimakaviani commented on pkg/k8s/provider/provider.go
> +}
better to move the KindConfig definition under `pkg/k8s/providers/kind` for it to be self contained

2024-10-29 18:40 UTC, nabuskey commented
Closing this due to inactivity. Feel free to reopen.

2024-10-29 18:40 UTC, closed without merging